[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "https://ccsadvogados.com.br/*"
  to = "https://www.agenciadeinteligencia.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://ccsadvogados.com.br/*"
  to = "https://www.agenciadeinteligencia.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://agenciadeinteligencia.com.br/*"
  to = "https://www.agenciadeinteligencia.com.br/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://agenciadeinteligencia.com.br/*"
  to = "https://www.agenciadeinteligencia.com.br/:splat"
  status = 301
  force = true

# Configurações de cabeçalhos para melhorar a segurança e SEO
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.google-analytics.com https://www.googletagmanager.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com data:; img-src 'self' data: https:; connect-src 'self' https://www.google-analytics.com;"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
    
# Cache control para arquivos estáticos
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Configuração de segurança para o diretório de uploads
[[headers]]
  for = "/uploads/*"
  [headers.values]
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
